# Generated by Django 6.0.4 on 2026-04-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tutorials/')),
                ('content', models.TextField(help_text='Short overview content')),
                ('category', models.CharField(choices=[('PCB Design', 'PCB Design'), ('Embedded Systems', 'Embedded Systems'), ('Power Electronics', 'Power Electronics'), ('IoT', 'IoT'), ('Programming', 'Programming'), ('Other', 'Other')], max_length=50)),
                ('introduction', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutorials/sections/')),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tutorials.tutorial')),
            ],
            options={
                'verbose_name': 'Tutorial Section',
                'verbose_name_plural': 'Tutorial Sections',
                'ordering': ['order'],
            },
        ),
    ]
